INSERT INTO items (name, description, price, category, image, store_id)
VALUES
  ('Apple', 'Juicy and crisp Red Delicious apples', 2.99, 'Fruit', 'https://render.fineartamerica.com/images/rendered/default/poster/8/8/break/images-medium-5/apple-science-photo-library.jpg', 1),
  ('Banana', 'Yellow and ripe bananas', 3.99, 'Fruit', 'https://example.com/banana.jpg', 2),
  ('Carrot', 'Orange and crunchy carrots', 1.79, 'Vegetable', 'https://example.com/carrot.jpg', 3),
  ('Lettuce', 'Crispy and fresh green lettuce', 4.79, 'Vegetable', 'https://example.com/lettuce.jpg', 4),
  ('Tomato', 'Red and juicy vine-ripe tomatoes', 2.99, 'Vegetable', 'https://example.com/tomato.jpg', 5), 
  ('Apple', 'Juicy and crisp Red Delicious apples', 4.99, 'Fruit', 'https://render.fineartamerica.com/images/rendered/default/poster/8/8/break/images-medium-5/apple-science-photo-library.jpg', 2),
  ('Banana', 'Yellow and ripe bananas', 1.34, 'Fruit', 'https://example.com/banana.jpg', 3),
  ('Carrot', 'Orange and crunchy carrots', 1.99, 'Vegetable', 'https://example.com/carrot.jpg', 4),
  ('Lettuce', 'Crispy and fresh green lettuce', 5.79, 'Vegetable', 'https://example.com/lettuce.jpg', 5),
  ('Tomato', 'Red and juicy vine-ripe tomatoes', 2.43, 'Vegetable', 'https://example.com/tomato.jpg', 1), 
  ('Apple', 'Juicy and crisp Red Delicious apples', 2.99, 'Fruit', 'https://render.fineartamerica.com/images/rendered/default/poster/8/8/break/images-medium-5/apple-science-photo-library.jpg', 3),
  ('Banana', 'Yellow and ripe bananas', 1.99, 'Fruit', 'https://example.com/banana.jpg', 4),
  ('Carrot', 'Orange and crunchy carrots', 3.49, 'Vegetable', 'https://example.com/carrot.jpg', 5),
  ('Lettuce', 'Crispy and fresh green lettuce', 6.79, 'Vegetable', 'https://example.com/lettuce.jpg', 1),
  ('Tomato', 'Red and juicy vine-ripe tomatoes', 2.99, 'Vegetable', 'https://example.com/tomato.jpg', 2), 
  ('Apple', 'Juicy and crisp Red Delicious apples', 2.69, 'Fruit', 'https://render.fineartamerica.com/images/rendered/default/poster/8/8/break/images-medium-5/apple-science-photo-library.jpg', 4),
  ('Banana', 'Yellow and ripe bananas', 1.22, 'Fruit', 'https://example.com/banana.jpg', 5),
  ('Carrot', 'Orange and crunchy carrots', 1.49, 'Vegetable', 'https://example.com/carrot.jpg', 1),
  ('Lettuce', 'Crispy and fresh green lettuce', 1.19, 'Vegetable', 'https://example.com/lettuce', 2),
   ('Tomato', 'Red and juicy vine-ripe tomatoes', 2.50, 'Vegetable', 'https://example.com/tomato.jpg', 3),
 ('Eggs' , 'Fresh and organic eggs', 3.50, 'Dairy', 'https://example.com/eggs.jpg', 1),
 ('Milk' , 'Fresh and organic milk', 4.99, 'Dairy', 'https://example.com/milk.jpg', 2),
 ('Cheese' , 'Fresh and organic cheese', 5.99, 'Dairy', 'https://example.com/cheese.jpg', 3),
 ('Butter' , 'Fresh and organic butter', 6.79, 'Dairy', 'https://example.com/butter.jpg', 4),
 ('Yogurt' , 'Fresh and organic yogurt', 7.39, 'Dairy', 'https://example.com/yogurt.jpg', 5),
 ('Eggs' , 'Fresh and organic eggs', 3.29, 'Dairy', 'https://example.com/eggs.jpg', 2),
 ('Milk' , 'Fresh and organic milk', 4.99, 'Dairy', 'https://example.com/milk.jpg', 3),
 ('Cheese' , 'Fresh and organic cheese', 5.99, 'Dairy', 'https://example.com/cheese.jpg', 4),
 ('Butter' , 'Fresh and organic butter', 6.99, 'Dairy', 'https://example.com/butter.jpg', 5),
 ('Yogurt' , 'Fresh and organic yogurt', 7.99, 'Dairy', 'https://example.com/yogurt.jpg', 1),
 ('Eggs' , 'Fresh and organic eggs', 3.99, 'Dairy', 'https://example.com/eggs.jpg', 3),
 ('Milk' , 'Fresh and organic milk', 4.99, 'Dairy', 'https://example.com/milk.jpg', 4),
 ('Cheese' , 'Fresh and organic cheese', 5.99, 'Dairy', 'https://example.com/cheese.jpg', 5),
 ('Butter' , 'Fresh and organic butter', 5.99, 'Dairy', 'https://example.com/butter.jpg', 1),
 ('Yogurt' , 'Fresh and organic yogurt', 7.00, 'Dairy', 'https://example.com/yogurt.jpg', 2),
  ('Eggs' , 'Fresh and organic eggs', 3.99, 'Dairy', 'https://example.com/eggs.jpg', 4),
  ('Milk' , 'Fresh and organic milk', 4.50, 'Dairy', 'https://example.com/milk.jpg', 5), 
  ('Peach', 'Sweet and juicy peaches', 3.99, 'Fruit', 'https://example.com/peach.jpg', 1),
('Blueberries', 'Sweet and plump blueberries', 5.99, 'Fruit', 'https://example.com/blueberries.jpg', 2),
('Strawberries', 'Sweet and juicy strawberries', 4.99, 'Fruit', 'https://example.com/strawberries.jpg', 3),
('Cherry', 'Sweet and juicy cherries', 6.99, 'Fruit', 'https://example.com/cherry.jpg', 4),
('Grapes', 'Sweet and juicy grapes', 7.99, 'Fruit', 'https://example.com/grapes.jpg', 5),
('Peach', 'Sweet and juicy peaches', 4.99, 'Fruit', 'https://example.com/peach.jpg', 2),
('Blueberries', 'Sweet and plump blueberries', 6.99, 'Fruit', 'https://example.com/blueberries.jpg', 3),
('Strawberries', 'Sweet and juicy strawberries', 3.99, 'Fruit', 'https://example.com/strawberries.jpg', 4),
('Cherry', 'Sweet and juicy cherries', 5.99, 'Fruit', 'https://example.com/cherry.jpg', 5),
('Grapes', 'Sweet and juicy grapes', 8.99, 'Fruit', 'https://example.com/grapes.jpg', 1),
('Peach', 'Sweet and juicy peaches', 3.49, 'Fruit', 'https://example.com/peach.jpg', 3),
('Blueberries', 'Sweet and plump blueberries', 5.49, 'Fruit', 'https://example.com/blueberries.jpg', 4),
('Strawberries', 'Sweet and juicy strawberries', 4.49, 'Fruit', 'https://example.com/strawberries.jpg', 5),
('Cherry', 'Sweet and juicy cherries', 6.49, 'Fruit', 'https://example.com/cherry.jpg', 1),
('Grapes', 'Sweet and juicy grapes', 7.49, 'Fruit', 'https://example.com/grapes.jpg', 2),
('Potato', 'Golden and crispy potatoes', 2.99, 'Vegetable', 'https://example.com/potato.jpg', 1),
('Potato', 'Golden and crispy potatoes', 2.15, 'Vegetable', 'https://example.com/potato.jpg', 5),
('Onion', 'Sweet and juicy onions', 1.99, 'Vegetable', 'https://example.com/onion.jpg', 2),
('Garlic', 'Fragrant and pungent garlic', 3.99, 'Vegetable', 'https://example.com/garlic.jpg', 3),
('Spinach', 'Crunchy and fresh spinach', 2.99, 'Vegetable', 'https://example.com/spinach.jpg', 4),
('Bell pepper', 'Sweet and juicy bell peppers', 3.00, 'Vegetable', 'https://example.com/bellpepper.jpg', 5),
('Potato', 'Golden and crispy potatoes', 3.49, 'Vegetable', 'https://example.com/potato.jpg', 2),
('Onion', 'Sweet and juicy onions', 2.49, 'Vegetable', 'https://example.com/onion.jpg', 3), 
('Beaf Meat' , 'Fresh and organic beaf meat', 7.99, 'Meat', 'https://example.com/beaf.jpg', 1),
('Chicken Meat' , 'Fresh and organic chicken meat', 4.99, 'Meat', 'https://example.com/chicken.jpg', 2),
('Lamb Meat' , 'Fresh and organic lamb meat', 6.39, 'Meat', 'https://example.com/lamb.jpg', 4),
('Fish Meat' , 'Fresh and organic fish meat', 7.99, 'Meat', 'https://example.com/fish.jpg', 5),
('Beaf Meat' , 'Fresh and organic beaf meat', 6.99, 'Meat', 'https://example.com/beaf.jpg', 2),
('Chicken Meat' , 'Fresh and organic chicken meat', 5.99, 'Meat', 'https://example.com/chicken.jpg', 3),
('Lamb Meat' , 'Fresh and organic lamb meat', 7.99, 'Meat', 'https://example.com/lamb.jpg', 5),
('Cod' , 'Fresh and organic Salmon', 8.99, 'Meat', 'https://example.com/fish.jpg', 1),
('Beef Meat' , 'Fresh and organic beaf meat', 8.99, 'Meat', 'https://assets.shop.loblaws.ca/products/21125124/b2/en/front/21125124_front_a06_@2.png', 3),
('Chicken Meat' , 'Fresh and organic chicken meat', 4.59, 'Meat', 'https://i5.walmartimages.ca/images/Enlarge/765/017/605388765017.jpg', 4),
('Lamb Meat' , 'Fresh and organic lamb meat', 6.00, 'Meat', 'https://i5.walmartimages.ca/images/Enlarge/825/981/6000204825981.jpg', 1),
('Pineapple', 'Sweet and juicy pineapples', 3.99, 'Fruit', 'https://i5.walmartimages.ca/images/Enlarge/198/506/6000200198506.jpg', 1),
('Pineapple', 'Sweet and juicy pineapples', 4.59, 'Fruit', 'https://images.costcobusinessdelivery.com/ImageDelivery/imageService?profileId=12028466&itemId=8789&recipeName=680', 2),
('Pineapple', 'Sweet and juicy pineapples', 3.49, 'Fruit', 'https://images.albertsons-media.com/is/image/ABS/960131462?$ng-ecom-pdp-mobile$&defaultImage=Not_Available', 3),
('Pomegranate', 'Sweet and juicy pomegranates', 6.99, 'Fruit', 'https://i5.walmartimages.ca/images/Enlarge/-31/271/999999-31271.jpg', 1),
('Pomegranate', 'Sweet and juicy pomegranates', 7.99, 'Fruit', 'https://assets.shop.loblaws.ca/products/21123919/b2/en/front/21123919_front_a06_@2.png', 2),
('Pomegranate', 'Sweet and juicy pomegranates', 6.49, 'Fruit', 'https://images.costcobusinessdelivery.com/ImageDelivery/imageService?profileId=12027981&itemId=1480&recipeName=680', 3),
('Pomegranate', 'Sweet and juicy pomegranates', 5.99, 'Fruit', 'https://assets.shop.loblaws.ca/products/20134767001/b3/en/front/20134767001_front_a06_@2.png', 4),
('Pomegranate', 'Sweet and juicy pomegranates', 4.99, 'Fruit', 'https://assets.shop.loblaws.ca/products/20526015/b1/en/front/20526015_front_a01_@2.png', 5),
('Tangerine', 'Sweet and juicy tangerines', 3.99, 'Fruit', 'https://i5.walmartimages.ca/images/Enlarge/443/093/6000198443093.jpg', 1),
('Tangerine', 'Sweet and juicy tangerines', 4.59, 'Fruit', 'https://assets.shop.loblaws.ca/products/21024434001/b2/en/front/21024434001_front_a06_@2.png', 2),
('Tangerine', 'Sweet and juicy tangerines', 3.49, 'Fruit', 'https://www.theproducemoms.com/wp-content/uploads/2020/08/8.png', 3),
('Tangerine', 'Sweet and juicy tangerines', 2.99, 'Fruit', 'https://assets.shop.loblaws.ca/products/20864961001/b2/en/front/20864961001_front_a06_@2.png', 4),
('Tangerine', 'Sweet and juicy tangerines', 1.99, 'Fruit', 'https://images.albertsons-media.com/is/image/ABS/960057300?$ng-ecom-pdp-mobile$&defaultImage=Not_Available', 5),
('Watermelon', 'Sweet and juicy watermelons', 6.99, 'Fruit', 'https://i5.walmartimages.ca/images/Enlarge/125/981/6000200125981.jpg', 1),
('Watermelon', 'Sweet and juicy watermelons', 7.99, 'Fruit', 'https://assets.shop.loblaws.ca/products/21023094001/b1/en/front/21023094001_front_a01_@2.png', 2),
('Watermelon', 'Sweet and juicy watermelons', 6.49, 'Fruit', 'https://images.costcobusinessdelivery.com/ImageDelivery/imageService?profileId=12027981&itemId=4032&recipeName=680', 3),
('Watermelon', 'Sweet and juicy watermelons', 5.99, 'Fruit', 'https://assets.shop.loblaws.ca/products/20145379001/b2/en/front/20145379001_front_a06_@2.png', 4),
('Watermelon', 'Sweet and juicy watermelons', 4.99, 'Fruit', 'https://zallat.com/wp-content/uploads/2020/10/500x500-1381.jpg', 5),
('Mango', 'Sweet and juicy mongo', 3.99, 'Fruit', 'https://i5.walmartimages.ca/images/Enlarge/094/519/6000200094519.jpg', 1),
('Mango', 'Sweet and juicy mongo', 4.59, 'Fruit', 'https://images.costcobusinessdelivery.com/ImageDelivery/imageService?profileId=12027981&itemId=1323996&recipeName=680', 2),
('Mango', 'Sweet and juicy mongo', 3.49, 'Fruit', 'https://assets.shop.loblaws.ca/products/20121509001/b2/en/front/20121509001_front_a06_@2.png', 3),
('Mango', 'Sweet and juicy mongo', 2.99, 'Fruit', 'https://assets.shop.loblaws.ca/products/20059635001/b2/en/front/20059635001_front_a06_@2.png', 4),
('Mango', 'Sweet and juicy mongo', 3.99, 'Fruit', 'https://www.sobeys.com/wp-content/uploads/2020/07/mangoes-1.jpg', 5),
('Broccoli', 'Crunchy and nutritious broccoli', 3.99, 'Vegetable', 'https://i5.walmartimages.ca/images/Enlarge/094/505/6000200094505.jpg', 1),
('Broccoli', 'Crunchy and nutritious broccoli', 4.59, 'Vegetable', 'https://assets.shop.loblaws.ca/products/20145621001/b2/en/front/20145621001_front_a06_@2.png', 2),
('Broccoli', 'Crunchy and nutritious broccoli', 3.49, 'Vegetable', 'https://images.costcobusinessdelivery.com/ImageDelivery/imageService?profileId=12028466&itemId=5623&recipeName=680&viewId=1', 3),
('Broccoli', 'Crunchy and nutritious broccoli', 1.29, 'Vegetable', 'https://assets.shop.loblaws.ca/products/20145621001/b3/en/front/20145621001_front_a06_@2.png', 4),
('Broccoli', 'Crunchy and nutritious broccoli', 1.99, 'Vegetable', 'https://zallat.com/wp-content/uploads/2020/10/x500x500-1414.jpg.pagespeed.ic.4ZdRQOdGP1.webp', 5),
('Cauliflower', 'Crunchy and nutritious cauliflower', 4.99, 'Vegetable', 'https://i5.walmartimages.ca/images/Large/272/324/6000191272324.jpg', 1),
('Cauliflower', 'Crunchy and nutritious cauliflower', 5.99, 'Vegetable', 'https://assets.shop.loblaws.ca/products/20135377001/b2/en/front/20135377001_front_a06_@2.png', 2),
('Cauliflower', 'Crunchy and nutritious cauliflower', 4.00, 'Vegetable', 'https://images.costcobusinesscentre.ca/ImageDelivery/imageService?profileId=12027981&imageId=760770__1&recipeName=350', 3),
('Cauliflower', 'Crunchy and nutritious cauliflower', 5.49, 'Vegetable', 'https://assets.shop.loblaws.ca/products/20001440001/b2/en/front/20001440001_front_a06_@2.png', 4),
('Cauliflower', 'Crunchy and nutritious cauliflower', 4.19, 'Vegetable', 'https://voila.ca/images-v3/2d92d19c-0354-49c0-8a91-5260ed0bf531/f4d498fd-2423-41c1-aef2-3835b65c030f/500x500.jpg', 5);
  



