DROP TABLE IF EXISTS sdfsdfsdf CASCADE;
CREATE TABLE wwwww (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL
);
